version: '3'

services:
    db:
        image: mysql:5.7
        container_name: routine_db
        volumes:
            - ./db/conf.d:/etc/mysql/conf.d
            - ./db/data:/var/lib/mysql
            - ./db/initdb.d:/docker-entrypoint-initdb.d
        env_file: .env
        environment:
            TZ: Asia/Seoul
        ports:
            - 3306:3306
        restart: always
    apiserver:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: routine_api
        volumes:
            - ./:/app/
        ports: 
            - 8003:8003
        depends_on:
            - db
        restart: always