# Generated by Django 4.0.3 on 2022-04-07 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
    ]
