# Generated by Django 4.0.3 on 2022-04-08 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'managed': False},
        ),
    ]
