# Generated by Django 4.0.3 on 2022-04-08 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0004_alter_account_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='account',
        ),
    ]
