# Generated by Django 4.0.3 on 2022-04-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0005_alter_account_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('routine_id', models.AutoField(primary_key=True, serialize=False)),
                ('account_id', models.PositiveIntegerField()),
                ('category_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('is_alarm', models.PositiveSmallIntegerField()),
                ('is_deleted', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'routine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoutineDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('routine_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'routine_day',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoutineResult',
            fields=[
                ('routine_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('routine_id', models.PositiveIntegerField()),
                ('result_id', models.PositiveIntegerField()),
                ('is_deleted', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'routine_result',
                'managed': False,
            },
        ),
    ]
