# Generated by Django 4.0.3 on 2022-04-08 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0006_category_routine_routineday_routineresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoutineResult',
        ),
    ]
