# Generated by Django 4.0.3 on 2022-04-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0007_delete_routineresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineResult',
            fields=[
                ('routine_result_id', models.AutoField(primary_key=True, serialize=False)),
                ('routine_id', models.PositiveIntegerField()),
                ('result_id', models.PositiveIntegerField()),
                ('is_deleted', models.SmallIntegerField()),
                ('created_at', models.DateTimeField()),
                ('modified_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'routine_result',
                'managed': False,
            },
        ),
    ]
